### Read all users
GET http://localhost:3000/users

### Read a user by ID
GET http://localhost:3000/users/1

### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "id":2,
    "name":"vikas",
    "age":20
}


### Update a user
PUT  http://localhost:3000/users
Content-Type: application/json

{
    "id":2,
    "name":"bhanu",
    "age":22
}


### Delete a user by ID
DELETE  http://localhost:3000/users/2





### Create a product
POST http://localhost:3000/product
Content-Type: application/json

{
    "productId":2,
    "pName":"Watch",
    "pBrand":"Samsung",
    "price":50000
}

### Read all products
GET http://localhost:3000/product

### Read all products by brand
GET http://localhost:3000/product/Apple

### Update a product
PUT http://localhost:3000/product
Content-Type: application/json

{
    "productId":1,
    "pName":"Phone",
    "pBrand":"Samsung",
    "price":100000
}


### Delete product by id
DELETE http://localhost:3000/product/1
